// Downloads the Assistant font (woff2) from Google Fonts and generates a local
// @font-face stylesheet, so the site self-hosts fonts (no render-blocking request).
import { mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dir = dirname(fileURLToPath(import.meta.url));
const base = join(__dir, '..');
const fontsDir = join(base, 'public/fonts');
mkdirSync(fontsDir, { recursive: true });

const CSS_URL = 'https://fonts.googleapis.com/css2?family=Assistant:wght@400;600;700;800&display=swap';
// A modern browser UA so Google returns woff2.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';

const res = await fetch(CSS_URL, { headers: { 'User-Agent': UA } });
const css = await res.text();

// Parse each @font-face block.
const blocks = css.split('@font-face').slice(1);
const faces = [];
let i = 0;
for (const blk of blocks) {
  const weight = (blk.match(/font-weight:\s*(\d+)/) || [])[1] || '400';
  const url = (blk.match(/src:\s*url\(([^)]+\.woff2)\)/) || [])[1];
  const range = (blk.match(/unicode-range:\s*([^;]+);/) || [])[1] || '';
  if (!url) continue;
  const isHebrew = /U\+0590|U\+05[0-9A-F]{2}/i.test(range);
  const subset = isHebrew ? 'hebrew' : (/U\+0000|U\+0041/i.test(range) ? 'latin' : 'ext');
  // Only keep hebrew + latin to stay lean.
  if (subset === 'ext') continue;
  const fname = `assistant-${weight}-${subset}.woff2`;
  const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
  writeFileSync(join(fontsDir, fname), buf);
  faces.push({ weight, subset, fname, range, size: buf.length });
  i++;
}

// Build @font-face CSS.
let out = '/* Self-hosted Assistant font (generated by scripts/fetch-fonts.mjs) */\n';
for (const f of faces) {
  out += `@font-face{font-family:'Assistant';font-style:normal;font-weight:${f.weight};font-display:swap;src:url('/fonts/${f.fname}') format('woff2');unicode-range:${f.range};}\n`;
}
writeFileSync(join(base, 'src/styles/fonts.css'), out, 'utf8');

console.log(`Downloaded ${faces.length} woff2 files:`);
faces.forEach((f) => console.log(`  ${f.subset} ${f.weight}  ${(f.size / 1024).toFixed(1)}KB  ${f.fname}`));
console.log('\nHebrew files for preload:');
faces.filter((f) => f.subset === 'hebrew' && ['400', '700'].includes(f.weight)).forEach((f) => console.log('  /fonts/' + f.fname));
