import puppeteer from "puppeteer-core";
import { existsSync } from "node:fs";
const EDGE = ["C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe","C:/Program Files/Microsoft/Edge/Application/msedge.exe"].find(existsSync);
const b = await puppeteer.launch({ executablePath: EDGE, headless: "new", args: ["--no-sandbox"] });
const p = await b.newPage();
await p.setViewport({ width: 390, height: 360, isMobile: true });
await p.goto("http://127.0.0.1:4321/", { waitUntil: "networkidle0" });
const topbar = await p.evaluate(() => getComputedStyle(document.querySelector(".topbar")).display);
console.log("mobile topbar display:", topbar);
await p.screenshot({ path: "_source/hdr-mobile.png" });
await b.close();
